module.exports = [
    // Pretos, cinzas e brancos
    { name: 'Preto Absoluto', hex: '#000000' },
    { name: 'Preto', hex: '#000001' },
    { name: 'Preto Ônix', hex: '#0F0F0F' },
    { name: 'Preto Ébano', hex: '#1C1C1C' },
    { name: 'Preto Carvão', hex: '#101820' },
    { name: 'Preto Grafite', hex: '#2A2A2A' },
    { name: 'Carvão', hex: '#36454F' },
    { name: 'Grafite', hex: '#41424C' },
    { name: 'Cinza Carvão', hex: '#333333' },
    { name: 'Cinza Chumbo', hex: '#555555' },
    { name: 'Cinza Escuro', hex: '#696969' },
    { name: 'Cinza Ferro', hex: '#43464B' },
    { name: 'Cinza Ardósia Escuro', hex: '#2F4F4F' },
    { name: 'Cinza Ardósia', hex: '#708090' },
    { name: 'Cinza Ardósia Claro', hex: '#778899' },
    { name: 'Cinza', hex: '#808080' },
    { name: 'Cinza Médio', hex: '#A9A9A9' },
    { name: 'Cinza Claro', hex: '#D3D3D3' },
    { name: 'Cinza Pérola', hex: '#EAEAEA' },
    { name: 'Cinza Névoa', hex: '#C5C6C7' },
    { name: 'Cinza Pedra', hex: '#928E85' },
    { name: 'Cinza Fumaça', hex: '#738276' },
    { name: 'Cinza Concreto', hex: '#8A8A8A' },
    { name: 'Prata', hex: '#C0C0C0' },
    { name: 'Prata Clara', hex: '#D9D9D9' },
    { name: 'Prata Escura', hex: '#A7A7A7' },
    { name: 'Prata Antiga', hex: '#848482' },
    { name: 'Platina', hex: '#E5E4E2' },
    { name: 'Branco Fumaça', hex: '#F5F5F5' },
    { name: 'Branco Fantasma', hex: '#F8F8FF' },
    { name: 'Branco Neve', hex: '#FFFAFA' },
    { name: 'Branco Gelo', hex: '#F0FFFF' },
    { name: 'Branco', hex: '#FFFFFF' },
    { name: 'Branco Pérola', hex: '#FDFDF5' },
    { name: 'Branco Antigo', hex: '#FAEBD7' },
    { name: 'Marfim', hex: '#FFFFF0' },
    { name: 'Creme', hex: '#FFFDD0' },
    { name: 'Osso', hex: '#E3DAC9' },
    { name: 'Baunilha', hex: '#F3E5AB' },

    // Azuis
    { name: 'Azul Meia-Noite', hex: '#191970' },
    { name: 'Azul Marinho', hex: '#000080' },
    { name: 'Azul Escuro', hex: '#00008B' },
    { name: 'Azul Profundo', hex: '#000033' },
    { name: 'Azul Cobalto', hex: '#0047AB' },
    { name: 'Azul Ultramarino', hex: '#120A8F' },
    { name: 'Azul Prussiano', hex: '#003153' },
    { name: 'Azul Berlim', hex: '#00304E' },
    { name: 'Azul Real', hex: '#4169E1' },
    { name: 'Azul', hex: '#0000FF' },
    { name: 'Azul Médio', hex: '#0000CD' },
    { name: 'Azul Cornflower', hex: '#6495ED' },
    { name: 'Azul Ardósia', hex: '#6A5ACD' },
    { name: 'Azul Ardósia Escuro', hex: '#483D8B' },
    { name: 'Azul Dodger', hex: '#1E90FF' },
    { name: 'Azul Céu Profundo', hex: '#00BFFF' },
    { name: 'Azul Céu', hex: '#87CEEB' },
    { name: 'Azul Céu Claro', hex: '#87CEFA' },
    { name: 'Azul Claro', hex: '#ADD8E6' },
    { name: 'Azul Aço', hex: '#4682B4' },
    { name: 'Azul Aço Claro', hex: '#B0C4DE' },
    { name: 'Azul Petróleo', hex: '#005F73' },
    { name: 'Azul Cerúleo', hex: '#007BA7' },
    { name: 'Azul Celeste', hex: '#4997D0' },
    { name: 'Azul Safira', hex: '#0F52BA' },
    { name: 'Azul Elétrico', hex: '#7DF9FF' },
    { name: 'Azul Neon', hex: '#1F51FF' },
    { name: 'Azul Pastel', hex: '#AEC6CF' },
    { name: 'Azul Bebê', hex: '#89CFF0' },
    { name: 'Azul Bebê Claro', hex: '#BFEFFF' },
    { name: 'Azul Piscina', hex: '#00AEEF' },
    { name: 'Azul Oceano', hex: '#0077BE' },
    { name: 'Azul Mar', hex: '#006994' },
    { name: 'Azul Profundo do Mar', hex: '#003B5C' },
    { name: 'Azul Royal Claro', hex: '#4169E1' },
    { name: 'Azul Denim', hex: '#1560BD' },
    { name: 'Azul Jeans', hex: '#1560BD' },
    { name: 'Azul Tiffany', hex: '#0ABAB5' },
    { name: 'Azul Turquesa', hex: '#00CED1' },
    { name: 'Azul Maya', hex: '#73C2FB' },
    { name: 'Azul Egípcio', hex: '#1034A6' },
    { name: 'Azul Pó', hex: '#B0E0E6' },
    { name: 'Azul Lavanda', hex: '#CCCCFF' },
    { name: 'Azul Periwinkle', hex: '#CCCCFF' },
    { name: 'Azul Acinzentado', hex: '#6699CC' },
    { name: 'Azul Cinzento', hex: '#6699CC' },
    { name: 'Azul Índigo Claro', hex: '#5D76A9' },
    { name: 'Azul Eclipse', hex: '#293133' },

    // Cianos e turquesas
    { name: 'Ciano', hex: '#00FFFF' },
    { name: 'Aqua', hex: '#00FFFF' },
    { name: 'Ciano Escuro', hex: '#008B8B' },
    { name: 'Ciano Claro', hex: '#E0FFFF' },
    { name: 'Turquesa Escuro', hex: '#00CED1' },
    { name: 'Turquesa', hex: '#40E0D0' },
    { name: 'Turquesa Médio', hex: '#48D1CC' },
    { name: 'Turquesa Claro', hex: '#AFEEEE' },
    { name: 'Turquesa Pálido', hex: '#B2DFDB' },
    { name: 'Verde-Água', hex: '#7FFFD4' },
    { name: 'Aquamarina', hex: '#7FFFD4' },
    { name: 'Aquamarina Médio', hex: '#66CDAA' },
    { name: 'Verde-Mar Claro', hex: '#20B2AA' },
    { name: 'Verde-Mar Escuro', hex: '#008B8B' },
    { name: 'Teal', hex: '#008080' },
    { name: 'Teal Escuro', hex: '#014D4E' },
    { name: 'Verde Água Claro', hex: '#B0F2B6' },
    { name: 'Espuma do Mar', hex: '#93E9BE' },
    { name: 'Onda do Mar', hex: '#4F42B5' },

    // Verdes
    { name: 'Verde Escuro', hex: '#006400' },
    { name: 'Verde', hex: '#008000' },
    { name: 'Verde Floresta', hex: '#228B22' },
    { name: 'Verde Pinheiro', hex: '#01796F' },
    { name: 'Verde Esmeralda', hex: '#50C878' },
    { name: 'Verde Jade', hex: '#00A86B' },
    { name: 'Verde Menta', hex: '#98FF98' },
    { name: 'Verde Hortelã', hex: '#3EB489' },
    { name: 'Verde Lima', hex: '#32CD32' },
    { name: 'Lima', hex: '#00FF00' },
    { name: 'Verde Neon', hex: '#39FF14' },
    { name: 'Verde Grama', hex: '#7CFC00' },
    { name: 'Verde Primavera', hex: '#00FF7F' },
    { name: 'Verde Primavera Médio', hex: '#00FA9A' },
    { name: 'Verde Amarelado', hex: '#ADFF2F' },
    { name: 'Verde Amarelo', hex: '#9ACD32' },
    { name: 'Verde Pálido', hex: '#98FB98' },
    { name: 'Verde Claro', hex: '#90EE90' },
    { name: 'Verde-Mar Escuro', hex: '#8FBC8F' },
    { name: 'Verde-Mar Médio', hex: '#3CB371' },
    { name: 'Verde-Mar', hex: '#2E8B57' },
    { name: 'Verde Oliva', hex: '#808000' },
    { name: 'Verde Oliva Drab', hex: '#6B8E23' },
    { name: 'Verde Cáqui', hex: '#556B2F' },
    { name: 'Verde Musgo', hex: '#8A9A5B' },
    { name: 'Verde Abacate', hex: '#568203' },
    { name: 'Verde Militar', hex: '#4B5320' },
    { name: 'Verde Sálvia', hex: '#9CAF88' },
    { name: 'Verde Eucalipto', hex: '#5F8575' },
    { name: 'Verde Pistache', hex: '#93C572' },
    { name: 'Verde Maçã', hex: '#8DB600' },
    { name: 'Verde Abacate Claro', hex: '#B5CC39' },
    { name: 'Verde Samambaia', hex: '#4F7942' },
    { name: 'Verde Trevo', hex: '#009E60' },
    { name: 'Verde Garrafa', hex: '#006A4E' },
    { name: 'Verde Garrafa Escuro', hex: '#004225' },
    { name: 'Verde Caçador', hex: '#355E3B' },
    { name: 'Verde Floresta Escuro', hex: '#014421' },
    { name: 'Verde Imperial', hex: '#005A36' },
    { name: 'Verde Malaquita', hex: '#0BDA51' },
    { name: 'Verde Viridiano', hex: '#40826D' },
    { name: 'Verde Primavera Claro', hex: '#7CFC00' },
    { name: 'Verde Lima Claro', hex: '#BFFF00' },
    { name: 'Verde Neon Claro', hex: '#66FF00' },

    // Amarelos
    { name: 'Amarelo', hex: '#FFFF00' },
    { name: 'Amarelo Claro', hex: '#FFFFE0' },
    { name: 'Amarelo Pálido', hex: '#FAFAD2' },
    { name: 'Amarelo Limão', hex: '#FFF44F' },
    { name: 'Amarelo Neon', hex: '#DFFF00' },
    { name: 'Amarelo Milho', hex: '#FFF380' },
    { name: 'Amarelo Dourado', hex: '#FFD700' },
    { name: 'Ouro', hex: '#FFD700' },
    { name: 'Dourado', hex: '#DAA520' },
    { name: 'Dourado Escuro', hex: '#B8860B' },
    { name: 'Amarelo Cáqui', hex: '#F0E68C' },
    { name: 'Mostarda', hex: '#FFDB58' },
    { name: 'Âmbar', hex: '#FFBF00' },
    { name: 'Açafrão', hex: '#F4C430' },
    { name: 'Amarelo Banana', hex: '#FFE135' },
    { name: 'Amarelo Canário', hex: '#FFEF00' },
    { name: 'Amarelo Mel', hex: '#FFC30B' },
    { name: 'Amarelo Manteiga', hex: '#FFFD74' },
    { name: 'Amarelo Creme', hex: '#FFFDD0' },
    { name: 'Amarelo Solar', hex: '#FFD300' },
    { name: 'Amarelo Açafrão Escuro', hex: '#E4D00A' },
    { name: 'Amarelo Ocre', hex: '#CC7722' },
    { name: 'Amarelo Limão Claro', hex: '#FFF700' },
    { name: 'Amarelo Girassol', hex: '#FFDA03' },

    // Laranjas
    { name: 'Laranja', hex: '#FFA500' },
    { name: 'Laranja Escuro', hex: '#FF8C00' },
    { name: 'Laranja Vermelho', hex: '#FF4500' },
    { name: 'Laranja Neon', hex: '#FF5F1F' },
    { name: 'Laranja Queimado', hex: '#CC5500' },
    { name: 'Laranja Tangerina', hex: '#F28500' },
    { name: 'Tangerina', hex: '#FF9966' },
    { name: 'Abóbora', hex: '#FF7518' },
    { name: 'Pêssego', hex: '#FFE5B4' },
    { name: 'Pêssego Claro', hex: '#FFDAB9' },
    { name: 'Damasco', hex: '#FBCEB1' },
    { name: 'Coral', hex: '#FF7F50' },
    { name: 'Coral Claro', hex: '#F88379' },
    { name: 'Tomate', hex: '#FF6347' },
    { name: 'Laranja Cenoura', hex: '#ED9121' },
    { name: 'Laranja Ferrugem', hex: '#B7410E' },
    { name: 'Laranja Abóbora', hex: '#FF7518' },
    { name: 'Laranja Melão', hex: '#FFA62F' },
    { name: 'Laranja Âmbar', hex: '#FFBF00' },
    { name: 'Laranja Dourado', hex: '#F2A900' },
    { name: 'Laranja Queimado Escuro', hex: '#A0522D' },
    { name: 'Laranja Terracota', hex: '#E2725B' },
    { name: 'Laranja Mandarina', hex: '#F28500' },

    // Vermelhos
    { name: 'Vermelho', hex: '#FF0000' },
    { name: 'Vermelho Escuro', hex: '#8B0000' },
    { name: 'Vermelho Tijolo', hex: '#B22222' },
    { name: 'Vermelho Fogo', hex: '#FF4500' },
    { name: 'Vermelho Carmim', hex: '#960018' },
    { name: 'Carmesim', hex: '#DC143C' },
    { name: 'Escarlate', hex: '#FF2400' },
    { name: 'Vermelho Rubi', hex: '#E0115F' },
    { name: 'Vermelho Cereja', hex: '#D2042D' },
    { name: 'Vermelho Sangue', hex: '#8A0303' },
    { name: 'Vermelho Vinho', hex: '#722F37' },
    { name: 'Vermelho Borgonha', hex: '#800020' },
    { name: 'Borgonha', hex: '#800020' },
    { name: 'Bordô', hex: '#800000' },
    { name: 'Vermelho Vinho Claro', hex: '#C04040' },
    { name: 'Vermelho Coral', hex: '#FF4040' },
    { name: 'Vermelho Rosado', hex: '#F08080' },
    { name: 'Vermelho Tomate', hex: '#FF6347' },
    { name: 'Vermelho Cobre', hex: '#CB6D51' },
    { name: 'Vermelho Rubi Escuro', hex: '#9B111E' },
    { name: 'Vermelho Granada', hex: '#7B1113' },
    { name: 'Vermelho Ferrari', hex: '#FF2800' },
    { name: 'Vermelho Cardinal', hex: '#C41E3A' },
    { name: 'Vermelho Imperial', hex: '#ED2939' },
    { name: 'Vermelho Carmim Claro', hex: '#E32636' },
    { name: 'Vermelho Papoula', hex: '#E35335' },
    { name: 'Vermelho Maçã', hex: '#D90000' },
    { name: 'Vermelho Cereja Escuro', hex: '#990F02' },

    // Rosas
    { name: 'Rosa', hex: '#FFC0CB' },
    { name: 'Rosa Claro', hex: '#FFB6C1' },
    { name: 'Rosa Choque', hex: '#FF69B4' },
    { name: 'Rosa Quente', hex: '#FF69B4' },
    { name: 'Rosa Profundo', hex: '#FF1493' },
    { name: 'Rosa Neon', hex: '#FF10F0' },
    { name: 'Rosa Pastel', hex: '#FFD1DC' },
    { name: 'Rosa Bebê', hex: '#F4C2C2' },
    { name: 'Rosa Chá', hex: '#F4C2C2' },
    { name: 'Rosa Salmão', hex: '#FF91A4' },
    { name: 'Rosa Antigo', hex: '#C08081' },
    { name: 'Rosa Pálido', hex: '#DB7093' },
    { name: 'Rosa Fúcsia', hex: '#FF00FF' },
    { name: 'Rosa Algodão-Doce', hex: '#FFBCD9' },
    { name: 'Rosa Chiclete', hex: '#FFC1CC' },
    { name: 'Rosa Coral', hex: '#F88379' },
    { name: 'Rosa Pêssego', hex: '#FFDAB9' },
    { name: 'Rosa Melancia', hex: '#FC6C85' },
    { name: 'Rosa Framboesa', hex: '#E30B5D' },
    { name: 'Rosa Morango', hex: '#FC5A8D' },
    { name: 'Rosa Magenta', hex: '#CA1F7B' },
    { name: 'Rosa Escuro', hex: '#C71585' },
    { name: 'Rosa Ameixa', hex: '#8E4585' },
    { name: 'Rosa Pó', hex: '#DCAE96' },
    { name: 'Rosa Nude', hex: '#E3BC9A' },
    { name: 'Rosa Salmão Claro', hex: '#FFA07A' },

    // Roxos e violetas
    { name: 'Roxo', hex: '#A020F0' },
    { name: 'Roxo Escuro', hex: '#4B0082' },
    { name: 'Violeta', hex: '#EE82EE' },
    { name: 'Violeta Escuro', hex: '#9400D3' },
    { name: 'Violeta Azul', hex: '#8A2BE2' },
    { name: 'Violeta Elétrico', hex: '#8F00FF' },
    { name: 'Roxo Real', hex: '#7851A9' },
    { name: 'Roxo Ameixa', hex: '#DDA0DD' },
    { name: 'Ameixa', hex: '#DDA0DD' },
    { name: 'Orquídea', hex: '#DA70D6' },
    { name: 'Orquídea Média', hex: '#BA55D3' },
    { name: 'Roxo Médio', hex: '#9370DB' },
    { name: 'Roxo Ardósia Médio', hex: '#7B68EE' },
    { name: 'Magenta', hex: '#FF00FF' },
    { name: 'Magenta Escuro', hex: '#8B008B' },
    { name: 'Fúcsia', hex: '#FF00FF' },
    { name: 'Lavanda', hex: '#E6E6FA' },
    { name: 'Lilás', hex: '#C8A2C8' },
    { name: 'Malva', hex: '#E0B0FF' },
    { name: 'Berinjela', hex: '#614051' },
    { name: 'Ametista', hex: '#9966CC' },
    { name: 'Roxo Uva', hex: '#6F2DA8' },
    { name: 'Roxo Imperial', hex: '#602F6B' },
    { name: 'Roxo Vinho', hex: '#5B3256' },
    { name: 'Roxo Neon', hex: '#BC13FE' },
    { name: 'Roxo Pastel', hex: '#B39EB5' },
    { name: 'Roxo Lavanda', hex: '#967BB6' },
    { name: 'Roxo Violeta', hex: '#7F00FF' },
    { name: 'Púrpura', hex: '#800080' },
    { name: 'Púrpura Real', hex: '#7851A9' },
    { name: 'Púrpura Egípcia', hex: '#6C3082' },

    // Marrons e tons terrosos
    { name: 'Marrom', hex: '#A52A2A' },
    { name: 'Marrom Escuro', hex: '#654321' },
    { name: 'Marrom Chocolate', hex: '#7B3F00' },
    { name: 'Chocolate', hex: '#D2691E' },
    { name: 'Marrom Sela', hex: '#8B4513' },
    { name: 'Siena', hex: '#A0522D' },
    { name: 'Siena Queimada', hex: '#E97451' },
    { name: 'Peru', hex: '#CD853F' },
    { name: 'Areia', hex: '#C2B280' },
    { name: 'Marrom Arenoso', hex: '#F4A460' },
    { name: 'Marrom Rosado', hex: '#BC8F8F' },
    { name: 'Marrom Dourado', hex: '#996515' },
    { name: 'Canela', hex: '#D2691E' },
    { name: 'Caramelo', hex: '#AF6F09' },
    { name: 'Café', hex: '#6F4E37' },
    { name: 'Café Escuro', hex: '#4B3621' },
    { name: 'Castanho', hex: '#954535' },
    { name: 'Terracota', hex: '#E2725B' },
    { name: 'Ocre', hex: '#CC7722' },
    { name: 'Ocre Amarelo', hex: '#C2B280' },
    { name: 'Bronze', hex: '#CD7F32' },
    { name: 'Cobre', hex: '#B87333' },
    { name: 'Latão', hex: '#B5A642' },
    { name: 'Tan', hex: '#D2B48C' },
    { name: 'Madeira', hex: '#C19A6B' },
    { name: 'Nogueira', hex: '#773F1A' },
    { name: 'Mogno', hex: '#C04000' },
    { name: 'Castanho Avermelhado', hex: '#993300' },
    { name: 'Marrom Canela', hex: '#D2691E' },
    { name: 'Marrom Ferrugem', hex: '#B7410E' },
    { name: 'Marrom Terra', hex: '#7C4700' },
    { name: 'Marrom Barro', hex: '#9B7653' },
    { name: 'Marrom Café com Leite', hex: '#A67B5B' },
    { name: 'Marrom Caramelo', hex: '#C68E17' },
    { name: 'Marrom Castanha', hex: '#954535' },
    { name: 'Marrom Madeira Escura', hex: '#5C4033' },

    // Pastéis
    { name: 'Pastel Azul', hex: '#AEC6CF' },
    { name: 'Pastel Verde', hex: '#77DD77' },
    { name: 'Pastel Amarelo', hex: '#FDFD96' },
    { name: 'Pastel Laranja', hex: '#FFB347' },
    { name: 'Pastel Vermelho', hex: '#FF6961' },
    { name: 'Pastel Rosa', hex: '#FFD1DC' },
    { name: 'Pastel Roxo', hex: '#B39EB5' },
    { name: 'Pastel Lilás', hex: '#C8A2C8' },
    { name: 'Pastel Pêssego', hex: '#FFDAB9' },
    { name: 'Pastel Menta', hex: '#AAF0D1' },
    { name: 'Pastel Turquesa', hex: '#99E6D8' },
    { name: 'Pastel Coral', hex: '#F88379' },
    { name: 'Pastel Lavanda', hex: '#D8BFD8' },
    { name: 'Pastel Creme', hex: '#FFFDD0' },
    { name: 'Pastel Baunilha', hex: '#F3E5AB' },
    { name: 'Pastel Azul Bebê', hex: '#BFEFFF' },
    { name: 'Pastel Amarelo Claro', hex: '#FFFACD' },
    { name: 'Pastel Rosa Bebê', hex: '#F4C2C2' },

    // Cores de pedras preciosas
    { name: 'Esmeralda', hex: '#50C878' },
    { name: 'Jade', hex: '#00A86B' },
    { name: 'Rubi', hex: '#E0115F' },
    { name: 'Safira', hex: '#0F52BA' },
    { name: 'Ametista', hex: '#9966CC' },
    { name: 'Topázio', hex: '#FFC87C' },
    { name: 'Âmbar', hex: '#FFBF00' },
    { name: 'Opala', hex: '#A8C3BC' },
    { name: 'Pérola', hex: '#EAE0C8' },
    { name: 'Turmalina', hex: '#E62F8B' },
    { name: 'Granada', hex: '#7B1113' },
    { name: 'Água-Marinha', hex: '#7FFFD4' },
    { name: 'Citrino', hex: '#E4D00A' },
    { name: 'Turquesa Pedra', hex: '#40E0D0' },
    { name: 'Lápis-Lazúli', hex: '#26619C' },
    { name: 'Quartzo Rosa', hex: '#F7CAC9' },
    { name: 'Ônix', hex: '#353839' },
    { name: 'Obsidiana', hex: '#0B0B0B' },
    { name: 'Peridoto', hex: '#E6E200' },
    { name: 'Aventurina', hex: '#568203' },

    // Metálicas
    { name: 'Ouro', hex: '#FFD700' },
    { name: 'Ouro Velho', hex: '#CFB53B' },
    { name: 'Ouro Pálido', hex: '#E6BE8A' },
    { name: 'Ouro Rosa', hex: '#B76E79' },
    { name: 'Ouro Antigo', hex: '#CBA135' },
    { name: 'Prata', hex: '#C0C0C0' },
    { name: 'Prata Antiga', hex: '#848482' },
    { name: 'Platina', hex: '#E5E4E2' },
    { name: 'Bronze', hex: '#CD7F32' },
    { name: 'Bronze Antigo', hex: '#665D1E' },
    { name: 'Cobre', hex: '#B87333' },
    { name: 'Cobre Antigo', hex: '#6F4E37' },
    { name: 'Latão', hex: '#B5A642' },
    { name: 'Ferro', hex: '#43464B' },
    { name: 'Aço', hex: '#71797E' },
    { name: 'Titânio', hex: '#878681' },
    { name: 'Mercúrio', hex: '#BFC1C2' },

    // Azuis adicionais
    { name: 'Azul Capri', hex: '#00BFFF' },
    { name: 'Azul Marítimo', hex: '#1CA3EC' },
    { name: 'Azul Mediterrâneo', hex: '#1C77C3' },
    { name: 'Azul Pacífico', hex: '#1CA9C9' },
    { name: 'Azul Atlântico', hex: '#006994' },
    { name: 'Azul Horizonte', hex: '#7CB9E8' },
    { name: 'Azul Safira Claro', hex: '#1E90FF' },
    { name: 'Azul Safira Escuro', hex: '#082567' },
    { name: 'Azul Royal Escuro', hex: '#002366' },
    { name: 'Azul Oxford', hex: '#002147' },
    { name: 'Azul Yale', hex: '#00356B' },
    { name: 'Azul Harvard', hex: '#A41034' },
    { name: 'Azul Cambridge', hex: '#A3C1AD' },
    { name: 'Azul Persa', hex: '#1C39BB' },
    { name: 'Azul Cerúleo Escuro', hex: '#007BA7' },
    { name: 'Azul Ciano', hex: '#00FFFF' },
    { name: 'Azul Glacial', hex: '#B0E0E6' },
    { name: 'Azul Gelo', hex: '#D6F1FF' },
    { name: 'Azul Nevoeiro', hex: '#A4C2D8' },
    { name: 'Azul Denim Claro', hex: '#5B9BD5' },
    { name: 'Azul Denim Escuro', hex: '#2243B6' },
    { name: 'Azul Jeans Escuro', hex: '#1560BD' },
    { name: 'Azul Marinho Claro', hex: '#1974D2' },
    { name: 'Azul Elétrico Escuro', hex: '#0066FF' },
    { name: 'Azul Laser', hex: '#00BFFF' },
    { name: 'Azul Neon Claro', hex: '#4D4DFF' },

    // Verdes adicionais
    { name: 'Verde Floresta Profundo', hex: '#014421' },
    { name: 'Verde Floresta Claro', hex: '#228B22' },
    { name: 'Verde Pinheiro', hex: '#01796F' },
    { name: 'Verde Abeto', hex: '#005F46' },
    { name: 'Verde Musgo Escuro', hex: '#3A5F0B' },
    { name: 'Verde Musgo Claro', hex: '#8A9A5B' },
    { name: 'Verde Oliva Escuro', hex: '#556B2F' },
    { name: 'Verde Oliva Claro', hex: '#B5B35C' },
    { name: 'Verde Militar Escuro', hex: '#4B5320' },
    { name: 'Verde Exército', hex: '#4B5320' },
    { name: 'Verde Caqui', hex: '#78866B' },
    { name: 'Verde Pântano', hex: '#ACB78E' },
    { name: 'Verde Pinho', hex: '#2F4F2F' },
    { name: 'Verde Carvalho', hex: '#568203' },
    { name: 'Verde Folha', hex: '#71AA34' },
    { name: 'Verde Folhagem', hex: '#228B22' },
    { name: 'Verde Ervilha', hex: '#85BB65' },
    { name: 'Verde Pepino', hex: '#ACE1AF' },
    { name: 'Verde Abacate', hex: '#568203' },
    { name: 'Verde Maçã', hex: '#8DB600' },
    { name: 'Verde Kiwi', hex: '#8EE53F' },
    { name: 'Verde Pistache', hex: '#93C572' },
    { name: 'Verde Melão', hex: '#98FF98' },
    { name: 'Verde Menta Claro', hex: '#AAF0D1' },
    { name: 'Verde Hortelã Claro', hex: '#BDFCC9' },
    { name: 'Verde Neon', hex: '#39FF14' },
    { name: 'Verde Fluorescente', hex: '#7FFF00' },
    { name: 'Verde Ácido', hex: '#B0FF00' },
    { name: 'Verde Limão Escuro', hex: '#32CD32' },
    { name: 'Verde Esmeralda Escuro', hex: '#046307' },
    { name: 'Verde Esmeralda Claro', hex: '#80E35C' },
    { name: 'Verde Jade Escuro', hex: '#00A86B' },
    { name: 'Verde Jade Claro', hex: '#00A86B' },
    { name: 'Verde Malaquita', hex: '#0BDA51' },
    { name: 'Verde Viridiano', hex: '#40826D' },
    { name: 'Verde Celadon', hex: '#ACE1AF' },
    { name: 'Verde Sálvia', hex: '#9CAF88' },
    { name: 'Verde Eucalipto', hex: '#5F8575' },
    { name: 'Verde Abeto Claro', hex: '#2E8B57' },
    { name: 'Verde Primavera', hex: '#00FF7F' },
    { name: 'Verde Primavera Claro', hex: '#7CFC00' },
    { name: 'Verde Primavera Escuro', hex: '#177245' },

    // Amarelos adicionais
    { name: 'Amarelo Canário', hex: '#FFEF00' },
    { name: 'Amarelo Girassol', hex: '#FFDA03' },
    { name: 'Amarelo Banana', hex: '#FFE135' },
    { name: 'Amarelo Mel', hex: '#FFC30B' },
    { name: 'Amarelo Manteiga', hex: '#FFFD74' },
    { name: 'Amarelo Mostarda', hex: '#FFDB58' },
    { name: 'Amarelo Milho', hex: '#FFF380' },
    { name: 'Amarelo Açafrão', hex: '#F4C430' },
    { name: 'Amarelo Âmbar', hex: '#FFBF00' },
    { name: 'Amarelo Limão', hex: '#FFF44F' },
    { name: 'Amarelo Neon', hex: '#DFFF00' },
    { name: 'Amarelo Solar', hex: '#FFD300' },
    { name: 'Amarelo Dourado', hex: '#FFD700' },
    { name: 'Amarelo Ocre', hex: '#CC7722' },
    { name: 'Amarelo Palha', hex: '#E4D96F' },
    { name: 'Amarelo Areia', hex: '#F4E8C1' },
    { name: 'Amarelo Baunilha', hex: '#F3E5AB' },
    { name: 'Amarelo Creme', hex: '#FFFDD0' },
    { name: 'Amarelo Pastel', hex: '#FDFD96' },

    // Laranjas adicionais
    { name: 'Laranja Mandarina', hex: '#F28500' },
    { name: 'Laranja Tangerina', hex: '#FF9966' },
    { name: 'Laranja Abóbora', hex: '#FF7518' },
    { name: 'Laranja Cenoura', hex: '#ED9121' },
    { name: 'Laranja Manga', hex: '#FF8243' },
    { name: 'Laranja Pôr do Sol', hex: '#FD5E53' },
    { name: 'Laranja Coral', hex: '#FF7F50' },
    { name: 'Laranja Dourado', hex: '#F2A900' },
    { name: 'Laranja Ferrugem', hex: '#B7410E' },
    { name: 'Laranja Queimado', hex: '#CC5500' },
    { name: 'Laranja Cobre', hex: '#B87333' },
    { name: 'Laranja Âmbar', hex: '#FFBF00' },
    { name: 'Laranja Neon', hex: '#FF5F1F' },
    { name: 'Laranja Pêssego', hex: '#FFE5B4' },
    { name: 'Laranja Damasco', hex: '#FBCEB1' },

    // Vermelhos adicionais
    { name: 'Vermelho Escarlate', hex: '#FF2400' },
    { name: 'Vermelho Carmim', hex: '#960018' },
    { name: 'Vermelho Cardinal', hex: '#C41E3A' },
    { name: 'Vermelho Ferrari', hex: '#FF2800' },
    { name: 'Vermelho Rubi', hex: '#E0115F' },
    { name: 'Vermelho Granada', hex: '#7B1113' },
    { name: 'Vermelho Cereja', hex: '#D2042D' },
    { name: 'Vermelho Framboesa', hex: '#E30B5D' },
    { name: 'Vermelho Morango', hex: '#FC5A8D' },
    { name: 'Vermelho Melancia', hex: '#FC6C85' },
    { name: 'Vermelho Vinho', hex: '#722F37' },
    { name: 'Vermelho Borgonha', hex: '#800020' },
    { name: 'Vermelho Bordô', hex: '#800000' },
    { name: 'Vermelho Sangue', hex: '#8A0303' },
    { name: 'Vermelho Tijolo', hex: '#B22222' },
    { name: 'Vermelho Ferrugem', hex: '#B7410E' },
    { name: 'Vermelho Tomate', hex: '#FF6347' },
    { name: 'Vermelho Coral', hex: '#FF4040' },
    { name: 'Vermelho Neon', hex: '#FF073A' },
    { name: 'Vermelho Fluorescente', hex: '#FF3131' },
    { name: 'Vermelho Rubi Escuro', hex: '#9B111E' },
    { name: 'Vermelho Imperial', hex: '#ED2939' },

    // Rosas adicionais
    { name: 'Rosa Bebê', hex: '#F4C2C2' },
    { name: 'Rosa Algodão-Doce', hex: '#FFBCD9' },
    { name: 'Rosa Chiclete', hex: '#FFC1CC' },
    { name: 'Rosa Morango', hex: '#FC5A8D' },
    { name: 'Rosa Framboesa', hex: '#E30B5D' },
    { name: 'Rosa Melancia', hex: '#FC6C85' },
    { name: 'Rosa Coral', hex: '#F88379' },
    { name: 'Rosa Pêssego', hex: '#FFDAB9' },
    { name: 'Rosa Nude', hex: '#E3BC9A' },
    { name: 'Rosa Pó', hex: '#DCAE96' },
    { name: 'Rosa Antigo', hex: '#C08081' },
    { name: 'Rosa Chá', hex: '#F4C2C2' },
    { name: 'Rosa Neon', hex: '#FF10F0' },
    { name: 'Rosa Choque', hex: '#FF69B4' },
    { name: 'Rosa Profundo', hex: '#FF1493' },
    { name: 'Rosa Fúcsia', hex: '#FF00FF' },
    { name: 'Rosa Lavanda', hex: '#D8BFD8' },
    { name: 'Rosa Orquídea', hex: '#DA70D6' },

    // Roxos adicionais
    { name: 'Roxo Imperial', hex: '#602F6B' },
    { name: 'Roxo Real', hex: '#7851A9' },
    { name: 'Roxo Uva', hex: '#6F2DA8' },
    { name: 'Roxo Berinjela', hex: '#614051' },
    { name: 'Roxo Vinho', hex: '#5B3256' },
    { name: 'Roxo Neon', hex: '#BC13FE' },
    { name: 'Roxo Elétrico', hex: '#8F00FF' },
    { name: 'Roxo Ameixa', hex: '#DDA0DD' },
    { name: 'Roxo Lavanda', hex: '#967BB6' },
    { name: 'Roxo Pastel', hex: '#B39EB5' },
    { name: 'Roxo Amora', hex: '#5C164E' },
    { name: 'Roxo Violeta', hex: '#7F00FF' },
    { name: 'Roxo Framboesa', hex: '#915F6D' },
    { name: 'Roxo Púrpura', hex: '#800080' },
    { name: 'Violeta Floral', hex: '#8F00FF' },
    { name: 'Violeta Azul', hex: '#8A2BE2' },
    { name: 'Violeta Escuro', hex: '#9400D3' },
    { name: 'Lilás Claro', hex: '#D8BFD8' },
    { name: 'Lilás Escuro', hex: '#B57EDC' },
    { name: 'Lavanda Escura', hex: '#734F96' },

    // Marrons adicionais
    { name: 'Marrom Café', hex: '#6F4E37' },
    { name: 'Marrom Café Escuro', hex: '#4B3621' },
    { name: 'Marrom Chocolate', hex: '#7B3F00' },
    { name: 'Marrom Castanha', hex: '#954535' },
    { name: 'Marrom Mogno', hex: '#C04000' },
    { name: 'Marrom Nogueira', hex: '#773F1A' },
    { name: 'Marrom Canela', hex: '#D2691E' },
    { name: 'Marrom Caramelo', hex: '#AF6F09' },
    { name: 'Marrom Terra', hex: '#7C4700' },
    { name: 'Marrom Barro', hex: '#9B7653' },
    { name: 'Marrom Madeira', hex: '#C19A6B' },
    { name: 'Marrom Areia', hex: '#C2B280' },
    { name: 'Marrom Ferrugem', hex: '#B7410E' },
    { name: 'Marrom Bronze', hex: '#CD7F32' },
    { name: 'Marrom Cobre', hex: '#B87333' },
    { name: 'Marrom Dourado', hex: '#996515' },
    { name: 'Marrom Rosado', hex: '#BC8F8F' },

    // Tons naturais
    { name: 'Areia', hex: '#C2B280' },
    { name: 'Bege', hex: '#F5F5DC' },
    { name: 'Bege Claro', hex: '#F1E9D2' },
    { name: 'Bege Escuro', hex: '#C8AD7F' },
    { name: 'Creme', hex: '#FFFDD0' },
    { name: 'Marfim', hex: '#FFFFF0' },
    { name: 'Champanhe', hex: '#F7E7CE' },
    { name: 'Palha', hex: '#E4D96F' },
    { name: 'Trigo', hex: '#F5DEB3' },
    { name: 'Baunilha', hex: '#F3E5AB' },
    { name: 'Caramelo', hex: '#AF6F09' },
    { name: 'Mel', hex: '#EB9605' },
    { name: 'Café', hex: '#6F4E37' },
    { name: 'Terra', hex: '#8B4513' },
    { name: 'Argila', hex: '#B66A50' },
    { name: 'Terracota', hex: '#E2725B' },
    { name: 'Ocre', hex: '#CC7722' },
    { name: 'Siena', hex: '#A0522D' },
    { name: 'Siena Queimada', hex: '#E97451' },
    { name: 'Umber', hex: '#635147' },

    // Cores metálicas
    { name: 'Ouro', hex: '#FFD700' },
    { name: 'Ouro Velho', hex: '#CFB53B' },
    { name: 'Ouro Antigo', hex: '#CBA135' },
    { name: 'Ouro Rosa', hex: '#B76E79' },
    { name: 'Ouro Pálido', hex: '#E6BE8A' },
    { name: 'Prata', hex: '#C0C0C0' },
    { name: 'Prata Antiga', hex: '#848482' },
    { name: 'Platina', hex: '#E5E4E2' },
    { name: 'Bronze', hex: '#CD7F32' },
    { name: 'Bronze Antigo', hex: '#665D1E' },
    { name: 'Cobre', hex: '#B87333' },
    { name: 'Cobre Antigo', hex: '#6F4E37' },
    { name: 'Latão', hex: '#B5A642' },
    { name: 'Ferro', hex: '#43464B' },
    { name: 'Aço', hex: '#71797E' },
    { name: 'Titânio', hex: '#878681' },
    { name: 'Mercúrio', hex: '#BFC1C2' },
    { name: 'Níquel', hex: '#727472' },
    { name: 'Alumínio', hex: '#A8A9AD' },

    // Cores inspiradas em flores
    { name: 'Rosa Tulipa', hex: '#FF878D' },
    { name: 'Rosa Camélia', hex: '#F88379' },
    { name: 'Vermelho Papoula', hex: '#E35335' },
    { name: 'Violeta Orquídea', hex: '#DA70D6' },
    { name: 'Azul Hortênsia', hex: '#5C9DED' },
    { name: 'Roxo Lavanda', hex: '#B57EDC' },
    { name: 'Amarelo Girassol', hex: '#FFDA03' },
    { name: 'Laranja Calêndula', hex: '#EAA221' },
    { name: 'Vermelho Rosa', hex: '#FF007F' },
    { name: 'Rosa Peônia', hex: '#EEC9D2' },
    { name: 'Rosa Sakura', hex: '#FFB7C5' },
    { name: 'Branco Jasmim', hex: '#F8F8FF' },
    { name: 'Amarelo Dente-de-Leão', hex: '#FDD017' },
    { name: 'Azul Centáurea', hex: '#6495ED' },

    // Cores neon
    { name: 'Neon Azul', hex: '#4D4DFF' },
    { name: 'Neon Ciano', hex: '#00FFFF' },
    { name: 'Neon Verde', hex: '#39FF14' },
    { name: 'Neon Amarelo', hex: '#DFFF00' },
    { name: 'Neon Laranja', hex: '#FF5F1F' },
    { name: 'Neon Vermelho', hex: '#FF073A' },
    { name: 'Neon Rosa', hex: '#FF10F0' },
    { name: 'Neon Roxo', hex: '#BC13FE' },
    { name: 'Neon Magenta', hex: '#FF00FF' },

    // Cores escuras especiais
    { name: 'Azul Quase Preto', hex: '#02075D' },
    { name: 'Verde Quase Preto', hex: '#013220' },
    { name: 'Vermelho Quase Preto', hex: '#3B0000' },
    { name: 'Roxo Quase Preto', hex: '#120321' },
    { name: 'Marrom Quase Preto', hex: '#1B0F0A' },
    { name: 'Azul Eclipse', hex: '#293133' },
    { name: 'Verde Eclipse', hex: '#003B36' },
    { name: 'Vermelho Eclipse', hex: '#400000' },
    { name: 'Roxo Eclipse', hex: '#241023' },
    { name: 'Obsidiana', hex: '#0B0B0B' },
    { name: 'Ébano', hex: '#555D50' },
    { name: 'Ônix', hex: '#353839' },

        // Azuis extras
    { name: 'Azul Açafrão', hex: '#1F75FE' },
    { name: 'Azul Aciano', hex: '#2E5894' },
    { name: 'Azul Adriático', hex: '#3C8DAD' },
    { name: 'Azul Aéreo', hex: '#72A0C1' },
    { name: 'Azul Alexandrita', hex: '#0B6E69' },
    { name: 'Azul Anil', hex: '#4B0082' },
    { name: 'Azul Ártico', hex: '#B7E3F2' },
    { name: 'Azul Astral', hex: '#005F73' },
    { name: 'Azul Aurora', hex: '#00B4D8' },
    { name: 'Azul Bic', hex: '#0000CC' },
    { name: 'Azul Brilhante', hex: '#0070FF' },
    { name: 'Azul Capri Claro', hex: '#00C4FF' },
    { name: 'Azul Caribe', hex: '#00AEEF' },
    { name: 'Azul Cerúleo Claro', hex: '#9FD9EF' },
    { name: 'Azul Cristal', hex: '#A7D8DE' },
    { name: 'Azul Diamante', hex: '#B9E5FF' },
    { name: 'Azul Elétrico Claro', hex: '#66CCFF' },
    { name: 'Azul Fumê', hex: '#536878' },
    { name: 'Azul Índigo', hex: '#4B0082' },
    { name: 'Azul Íris', hex: '#5A4FCF' },
    { name: 'Azul Lago', hex: '#4F94CD' },
    { name: 'Azul Marinho Profundo', hex: '#001F3F' },
    { name: 'Azul Meia-Noite Claro', hex: '#191970' },
    { name: 'Azul Mirtilo', hex: '#4F86F7' },
    { name: 'Azul Nebulosa', hex: '#3A506B' },
    { name: 'Azul Noturno', hex: '#0A1172' },
    { name: 'Azul Olímpico', hex: '#008ECC' },
    { name: 'Azul Safira Médio', hex: '#0066CC' },
    { name: 'Azul Tempestade', hex: '#4B6A88' },
    { name: 'Azul Tropical', hex: '#00B7EB' },
    { name: 'Azul Universo', hex: '#1B1F3B' },
    { name: 'Azul Vapor', hex: '#D6F5FF' },
    { name: 'Azul Veneno', hex: '#0066FF' },
    { name: 'Azul Vulcânico', hex: '#263238' },

    // Cianos extras
    { name: 'Ciano Água', hex: '#00E5FF' },
    { name: 'Ciano Brilhante', hex: '#18FFFF' },
    { name: 'Ciano Elétrico', hex: '#00FFFF' },
    { name: 'Ciano Gelo', hex: '#B2EBF2' },
    { name: 'Ciano Marinho', hex: '#008C95' },
    { name: 'Ciano Neon', hex: '#00FFEF' },
    { name: 'Ciano Oceânico', hex: '#008B8B' },
    { name: 'Ciano Pastel', hex: '#A7FFEB' },
    { name: 'Ciano Turquesa', hex: '#00C9C8' },
    { name: 'Turquesa Elétrica', hex: '#00F5D4' },
    { name: 'Turquesa Neon', hex: '#00FFE0' },
    { name: 'Turquesa Oceânica', hex: '#008C8C' },
    { name: 'Turquesa Pastel', hex: '#99E6D8' },
    { name: 'Turquesa Tropical', hex: '#00D4AA' },

    // Verdes extras
    { name: 'Verde Abacaxi', hex: '#8DB600' },
    { name: 'Verde Água-Marinha', hex: '#7FFFD4' },
    { name: 'Verde Amazônia', hex: '#3B7A57' },
    { name: 'Verde Broto', hex: '#A8D08D' },
    { name: 'Verde Brilhante', hex: '#66FF00' },
    { name: 'Verde Caqui Claro', hex: '#B0C49A' },
    { name: 'Verde Campo', hex: '#4CBB17' },
    { name: 'Verde Cipreste', hex: '#2F4F4F' },
    { name: 'Verde Comum', hex: '#3CB371' },
    { name: 'Verde Cristal', hex: '#A7E8BD' },
    { name: 'Verde Esmeralda Médio', hex: '#2E8B57' },
    { name: 'Verde Floresta Médio', hex: '#228B22' },
    { name: 'Verde Folha Claro', hex: '#90C95A' },
    { name: 'Verde Frondoso', hex: '#3A9D23' },
    { name: 'Verde Goiaba', hex: '#8DB600' },
    { name: 'Verde Grama Claro', hex: '#90EE90' },
    { name: 'Verde Lima Neon', hex: '#BFFF00' },
    { name: 'Verde Limão', hex: '#CCFF00' },
    { name: 'Verde Louro', hex: '#A9BA9D' },
    { name: 'Verde Mata', hex: '#1B4D3E' },
    { name: 'Verde Melancia', hex: '#7AC74F' },
    { name: 'Verde Primavera Pastel', hex: '#C1FFC1' },
    { name: 'Verde Selva', hex: '#2E8B57' },
    { name: 'Verde Serpente', hex: '#4A7023' },
    { name: 'Verde Tropical', hex: '#00B140' },
    { name: 'Verde Uva', hex: '#597D35' },
    { name: 'Verde Veneno', hex: '#39FF14' },
    { name: 'Verde Flúor', hex: '#7FFF00' },

    // Amarelos extras
    { name: 'Amarelo Brilhante', hex: '#FFEA00' },
    { name: 'Amarelo Dourado Claro', hex: '#FFE066' },
    { name: 'Amarelo Enxofre', hex: '#FFFF66' },
    { name: 'Amarelo Flúor', hex: '#CCFF00' },
    { name: 'Amarelo Limão Neon', hex: '#DFFF00' },
    { name: 'Amarelo Ouro Claro', hex: '#FFE680' },
    { name: 'Amarelo Pérola', hex: '#FFF8DC' },
    { name: 'Amarelo Pêssego', hex: '#FFDAB9' },
    { name: 'Amarelo Pistache', hex: '#D4E157' },
    { name: 'Amarelo Tangerina', hex: '#FFC107' },
    { name: 'Amarelo Toffee', hex: '#D4A017' },
    { name: 'Amarelo Âmbar Claro', hex: '#FFD54F' },

    // Laranjas extras
    { name: 'Laranja Brilhante', hex: '#FF6700' },
    { name: 'Laranja Citrino', hex: '#F4A460' },
    { name: 'Laranja Dourado Claro', hex: '#FFC04C' },
    { name: 'Laranja Fogo', hex: '#FF5E00' },
    { name: 'Laranja Flúor', hex: '#FF8C00' },
    { name: 'Laranja Goiaba', hex: '#FF7F50' },
    { name: 'Laranja Manga Claro', hex: '#FFB347' },
    { name: 'Laranja Neon Claro', hex: '#FFAA00' },
    { name: 'Laranja Pôr do Sol', hex: '#FD5E53' },
    { name: 'Laranja Sangue', hex: '#FF4F00' },
    { name: 'Laranja Tangerina Claro', hex: '#FFAD60' },
    { name: 'Laranja Tropical', hex: '#FF7A00' },

    // Vermelhos extras
    { name: 'Vermelho Brilhante', hex: '#FF1744' },
    { name: 'Vermelho Carmesim Escuro', hex: '#B00020' },
    { name: 'Vermelho Cereja Claro', hex: '#FF4D6D' },
    { name: 'Vermelho Coral Claro', hex: '#FF6F61' },
    { name: 'Vermelho Escarlate Escuro', hex: '#B22222' },
    { name: 'Vermelho Framboesa Escuro', hex: '#C72C48' },
    { name: 'Vermelho Grená', hex: '#831D1C' },
    { name: 'Vermelho Lava', hex: '#CF1020' },
    { name: 'Vermelho Neon Claro', hex: '#FF3131' },
    { name: 'Vermelho Papoula Claro', hex: '#FF5A5F' },
    { name: 'Vermelho Sangue Escuro', hex: '#660000' },
    { name: 'Vermelho Vinho Escuro', hex: '#4C0013' },
    { name: 'Vermelho Vulcânico', hex: '#E34234' },

    // Rosas extras
    { name: 'Rosa Brilhante', hex: '#FF007F' },
    { name: 'Rosa Chá Claro', hex: '#F4C2C2' },
    { name: 'Rosa Cristal', hex: '#FDE2E4' },
    { name: 'Rosa Fúcsia Escuro', hex: '#C71585' },
    { name: 'Rosa Flamingo', hex: '#FC8EAC' },
    { name: 'Rosa Goiaba', hex: '#F88379' },
    { name: 'Rosa Hibisco', hex: '#E45C96' },
    { name: 'Rosa Magenta Claro', hex: '#F06292' },
    { name: 'Rosa Neon Claro', hex: '#FF69B4' },
    { name: 'Rosa Orquídea Claro', hex: '#E6A8D7' },
    { name: 'Rosa Pétala', hex: '#FADADD' },
    { name: 'Rosa Romã', hex: '#E30B5D' },
    { name: 'Rosa Rubi', hex: '#E0115F' },
    { name: 'Rosa Sakura Claro', hex: '#FFE4E1' },
    { name: 'Rosa Violeta', hex: '#DE5D83' },

    // Roxos extras
    { name: 'Roxo Brilhante', hex: '#9C27B0' },
    { name: 'Roxo Cereja', hex: '#7B1FA2' },
    { name: 'Roxo Cristal', hex: '#D8BFD8' },
    { name: 'Roxo Escuro Profundo', hex: '#301934' },
    { name: 'Roxo Elétrico Claro', hex: '#A020F0' },
    { name: 'Roxo Granada', hex: '#733635' },
    { name: 'Roxo Íris', hex: '#5D3FD3' },
    { name: 'Roxo Lavanda Claro', hex: '#B57EDC' },
    { name: 'Roxo Magenta', hex: '#9B26B6' },
    { name: 'Roxo Neon Claro', hex: '#CF00FF' },
    { name: 'Roxo Noturno', hex: '#32174D' },
    { name: 'Roxo Uva Escuro', hex: '#321450' },
    { name: 'Roxo Violeta Claro', hex: '#9F00FF' },
    { name: 'Púrpura Brilhante', hex: '#BF00FF' },
    { name: 'Púrpura Escuro', hex: '#4B0082' },

    // Bege, creme e tons claros
    { name: 'Bege Rosado', hex: '#E8C4A2' },
    { name: 'Bege Dourado', hex: '#D8B365' },
    { name: 'Bege Pêssego', hex: '#F5D0B5' },
    { name: 'Bege Areia', hex: '#E6D3A3' },
    { name: 'Bege Creme', hex: '#F3E5AB' },
    { name: 'Bege Acinzentado', hex: '#D8D2C4' },
    { name: 'Creme Dourado', hex: '#F5E6A8' },
    { name: 'Creme Rosado', hex: '#F8E0E0' },
    { name: 'Marfim Rosado', hex: '#FFF1E0' },
    { name: 'Marfim Dourado', hex: '#FFF8DC' },
    { name: 'Baunilha Clara', hex: '#FFF4CC' },
    { name: 'Baunilha Dourada', hex: '#F3E5AB' },

    // Tons terrosos extras
    { name: 'Barro Queimado', hex: '#A0522D' },
    { name: 'Barro Vermelho', hex: '#9E3D22' },
    { name: 'Terra Queimada', hex: '#8A3324' },
    { name: 'Terra Vermelha', hex: '#A94024' },
    { name: 'Terra Seca', hex: '#B88A65' },
    { name: 'Areia Dourada', hex: '#C9A66B' },
    { name: 'Areia Quente', hex: '#D2B48C' },
    { name: 'Areia Rosada', hex: '#E2B8A3' },
    { name: 'Argila Vermelha', hex: '#B7410E' },
    { name: 'Argila Queimada', hex: '#A45A52' },
    { name: 'Ocre Escuro', hex: '#8B5A2B' },
    { name: 'Ocre Dourado', hex: '#C68E17' },
    { name: 'Umber Queimado', hex: '#8A3324' },
    { name: 'Umber Natural', hex: '#826644' },

    // Tons de vinho e bordô
    { name: 'Vinho', hex: '#722F37' },
    { name: 'Vinho Escuro', hex: '#4C0013' },
    { name: 'Vinho Tinto', hex: '#990000' },
    { name: 'Vinho Rubi', hex: '#9B111E' },
    { name: 'Vinho Ameixa', hex: '#673147' },
    { name: 'Vinho Marsala', hex: '#964F4C' },
    { name: 'Bordô Escuro', hex: '#560319' },
    { name: 'Bordô Claro', hex: '#9E3A40' },
    { name: 'Borgonha Escura', hex: '#4A0010' },
    { name: 'Borgonha Clara', hex: '#9F1D35' },
    { name: 'Granada Escura', hex: '#5E1914' },

    // Cores de frutas
    { name: 'Vermelho Maçã', hex: '#E60026' },
    { name: 'Verde Maçã', hex: '#8DB600' },
    { name: 'Amarelo Banana', hex: '#FFE135' },
    { name: 'Laranja Laranja', hex: '#FFA500' },
    { name: 'Laranja Manga', hex: '#FF8243' },
    { name: 'Rosa Morango', hex: '#FC5A8D' },
    { name: 'Vermelho Framboesa', hex: '#E30B5D' },
    { name: 'Roxo Amora', hex: '#5C164E' },
    { name: 'Roxo Uva', hex: '#6F2DA8' },
    { name: 'Verde Kiwi', hex: '#8EE53F' },
    { name: 'Verde Abacate', hex: '#568203' },
    { name: 'Amarelo Limão', hex: '#FFF44F' },
    { name: 'Vermelho Romã', hex: '#E31837' },
    { name: 'Rosa Melancia', hex: '#FC6C85' },
    { name: 'Laranja Mamão', hex: '#FFB07C' },
    { name: 'Amarelo Manga', hex: '#FFCC33' },

    // Cores de natureza
    { name: 'Verde Floresta Profundo', hex: '#013220' },
    { name: 'Verde Selva Escuro', hex: '#004B23' },
    { name: 'Verde Mata Escuro', hex: '#0B3D2E' },
    { name: 'Verde Musgo Profundo', hex: '#354A21' },
    { name: 'Verde Folha Escuro', hex: '#2D572C' },
    { name: 'Verde Campo Escuro', hex: '#355E3B' },
    { name: 'Verde Prado', hex: '#4F7942' },
    { name: 'Verde Relva', hex: '#5CA904' },
    { name: 'Verde Floresta Tropical', hex: '#00755E' },
    { name: 'Verde Mata Atlântica', hex: '#006B3C' },
    { name: 'Verde Amazônico', hex: '#1B7F5C' },
    { name: 'Verde Pântano Escuro', hex: '#2F4538' },

    // Cores de céu e espaço
    { name: 'Azul Céu Profundo', hex: '#003366' },
    { name: 'Azul Horizonte Claro', hex: '#89CFF0' },
    { name: 'Azul Crepúsculo', hex: '#414A4C' },
    { name: 'Azul Amanhecer', hex: '#87CEFA' },
    { name: 'Azul Entardecer', hex: '#536878' },
    { name: 'Azul Aurora Boreal', hex: '#00A6A6' },
    { name: 'Roxo Nebulosa', hex: '#483D8B' },
    { name: 'Roxo Galáxia', hex: '#3C1361' },
    { name: 'Azul Galáxia', hex: '#1B1B3A' },
    { name: 'Azul Cosmos', hex: '#191970' },
    { name: 'Preto Espaço', hex: '#050505' },
    { name: 'Cinza Lunar', hex: '#B7B7B7' },
    { name: 'Branco Estelar', hex: '#F8F8FF' },

    // Cores de gelo e neve
    { name: 'Azul Gelo Claro', hex: '#E0F7FA' },
    { name: 'Azul Geada', hex: '#DFF6FF' },
    { name: 'Azul Neve', hex: '#EAF8FF' },
    { name: 'Ciano Glacial', hex: '#B2EBF2' },
    { name: 'Branco Glacial', hex: '#F0FFFF' },
    { name: 'Branco Geada', hex: '#F5FAFA' },
    { name: 'Branco Neve Claro', hex: '#FFFAFA' },
    { name: 'Azul Ártico Claro', hex: '#D6F1FF' },

    // Cores de fogo
    { name: 'Vermelho Lava', hex: '#CF1020' },
    { name: 'Vermelho Brasa', hex: '#E25822' },
    { name: 'Laranja Brasa', hex: '#FF7034' },
    { name: 'Laranja Chama', hex: '#FF5E00' },
    { name: 'Amarelo Chama', hex: '#FFD300' },
    { name: 'Amarelo Fogo', hex: '#FFAA00' },
    { name: 'Vermelho Fogo Intenso', hex: '#FF2400' },
    { name: 'Laranja Fogo Intenso', hex: '#FF4500' },
    { name: 'Dourado Fogo', hex: '#FFB300' },

    // Cores fluorescentes
    { name: 'Azul Fluorescente', hex: '#00FFFF' },
    { name: 'Ciano Fluorescente', hex: '#00FFEF' },
    { name: 'Verde Fluorescente', hex: '#7FFF00' },
    { name: 'Amarelo Fluorescente', hex: '#CCFF00' },
    { name: 'Laranja Fluorescente', hex: '#FF6600' },
    { name: 'Vermelho Fluorescente', hex: '#FF3131' },
    { name: 'Rosa Fluorescente', hex: '#FF1493' },
    { name: 'Roxo Fluorescente', hex: '#BF00FF' },

    // Tons quase pretos adicionais
    { name: 'Preto Azul', hex: '#020B2D' },
    { name: 'Preto Verde', hex: '#001A14' },
    { name: 'Preto Vermelho', hex: '#1A0000' },
    { name: 'Preto Roxo', hex: '#100018' },
    { name: 'Preto Marrom', hex: '#1A0F0A' },
    { name: 'Preto Cinza', hex: '#171717' },
    { name: 'Preto Petróleo', hex: '#001F1F' },
    { name: 'Preto Violeta', hex: '#160016' },

    // Tons metálicos adicionais
    { name: 'Ouro Brilhante', hex: '#FFD700' },
    { name: 'Ouro Champagne', hex: '#F7E7CE' },
    { name: 'Ouro Rosado', hex: '#E8B4B8' },
    { name: 'Ouro Escuro', hex: '#B8860B' },
    { name: 'Ouro Bronzeado', hex: '#B08D57' },
    { name: 'Prata Brilhante', hex: '#E8E8E8' },
    { name: 'Prata Azulada', hex: '#C0C8D0' },
    { name: 'Prata Fosca', hex: '#B4B4B4' },
    { name: 'Aço Azul', hex: '#4682B4' },
    { name: 'Aço Escuro', hex: '#43464B' },
    { name: 'Ferro Escuro', hex: '#2F353B' },
    { name: 'Cobre Brilhante', hex: '#DA8A67' },
    { name: 'Cobre Vermelho', hex: '#CB6D51' },
    { name: 'Bronze Dourado', hex: '#B08D57' },
    { name: 'Bronze Escuro', hex: '#8C7853' },

    // Cores de pedras e minerais adicionais
    { name: 'Esmeralda Escura', hex: '#046307' },
    { name: 'Esmeralda Clara', hex: '#80E35C' },
    { name: 'Rubi Escuro', hex: '#9B111E' },
    { name: 'Rubi Claro', hex: '#E0115F' },
    { name: 'Safira Escura', hex: '#082567' },
    { name: 'Safira Clara', hex: '#1E90FF' },
    { name: 'Ametista Escura', hex: '#563C5C' },
    { name: 'Ametista Clara', hex: '#9966CC' },
    { name: 'Topázio Azul', hex: '#43B3AE' },
    { name: 'Topázio Dourado', hex: '#FFC87C' },
    { name: 'Turmalina Rosa', hex: '#E62F8B' },
    { name: 'Turmalina Verde', hex: '#00A86B' },
    { name: 'Quartzo Fumê', hex: '#51484F' },
    { name: 'Quartzo Cristal', hex: '#F8F8FF' },
    { name: 'Quartzo Azul', hex: '#7CB9E8' },
    { name: 'Lápis-Lazúli Claro', hex: '#26619C' },
    { name: 'Lápis-Lazúli Escuro', hex: '#1E3A5F' },
    { name: 'Obsidiana Azul', hex: '#17202A' },
    { name: 'Obsidiana Verde', hex: '#0B3D2E' },
    { name: 'Obsidiana Roxa', hex: '#1B0B2E' },
    { name: 'Jade Imperial', hex: '#00A86B' },
    { name: 'Jade Escuro', hex: '#006A4E' },
    { name: 'Âmbar Escuro', hex: '#CC7722' },
    { name: 'Âmbar Claro', hex: '#FFBF00' },
    { name: 'Citrino Dourado', hex: '#E4D00A' },
    { name: 'Peridoto Claro', hex: '#E6E200' },

    // Cores fantasiosas
    { name: 'Azul Mágico', hex: '#5865F2' },
    { name: 'Roxo Mágico', hex: '#7F00FF' },
    { name: 'Rosa Mágico', hex: '#FF00CC' },
    { name: 'Verde Mágico', hex: '#00FF9D' },
    { name: 'Azul Arcano', hex: '#3F51B5' },
    { name: 'Roxo Arcano', hex: '#6A0DAD' },
    { name: 'Verde Arcano', hex: '#00A36C' },
    { name: 'Vermelho Arcano', hex: '#B00020' },
    { name: 'Azul Místico', hex: '#4169E1' },
    { name: 'Roxo Místico', hex: '#8A2BE2' },
    { name: 'Verde Místico', hex: '#00A86B' },
    { name: 'Rosa Místico', hex: '#C71585' },
    { name: 'Ciano Místico', hex: '#00CED1' },
    { name: 'Dourado Místico', hex: '#FFD700' },
    { name: 'Prata Mística', hex: '#C0C0C0' },

    // Cores de fantasia/neon
    { name: 'Azul Plasma', hex: '#00BFFF' },
    { name: 'Ciano Plasma', hex: '#00FFFF' },
    { name: 'Verde Plasma', hex: '#39FF14' },
    { name: 'Amarelo Plasma', hex: '#DFFF00' },
    { name: 'Laranja Plasma', hex: '#FF5F1F' },
    { name: 'Vermelho Plasma', hex: '#FF073A' },
    { name: 'Rosa Plasma', hex: '#FF10F0' },
    { name: 'Roxo Plasma', hex: '#BC13FE' },
    { name: 'Azul Laser', hex: '#0080FF' },
    { name: 'Verde Laser', hex: '#39FF14' },
    { name: 'Vermelho Laser', hex: '#FF3131' },
    { name: 'Roxo Laser', hex: '#A020F0' },
    { name: 'Rosa Laser', hex: '#FF1493' },
    { name: 'Ciano Laser', hex: '#00FFFF' },
];