module.exports = [
    { name: 'Black', hex: '#000000' },
    { name: 'Dim Gray', hex: '#696969' },
    { name: 'Gray', hex: '#808080' },
    { name: 'Dark Gray', hex: '#A9A9A9' },
    { name: 'Silver', hex: '#C0C0C0' },
    { name: 'Light Grey', hex: '#D3D3D3' },
    { name: 'Gainsboro', hex: '#DCDCDC' },

    { name: 'Navy', hex: '#000080' },
    { name: 'Dark Blue', hex: '#00008B' },
    { name: 'Medium Blue', hex: '#0000CD' },
    { name: 'Blue', hex: '#0000FF' },
    { name: 'Royal Blue', hex: '#4169E1' },
    { name: 'Dodger Blue', hex: '#1E90FF' },
    { name: 'Deep Sky Blue', hex: '#00BFFF' },
    { name: 'Sky Blue', hex: '#87CEEB' },
    { name: 'Light Blue', hex: '#ADD8E6' },

    { name: 'Aqua/Cyan', hex: '#00FFFF' },
    { name: 'Dark Turquoise', hex: '#00CED1' },
    { name: 'Turquoise', hex: '#40E0D0' },
    { name: 'Medium Turquoise', hex: '#48D1CC' },
    { name: 'Teal', hex: '#008080' },
    { name: 'Aquamarine', hex: '#7FFFD4' },

    { name: 'Dark Green', hex: '#006400' },
    { name: 'Green', hex: '#008000' },
    { name: 'Forest Green', hex: '#228B22' },
    { name: 'Lime Green', hex: '#32CD32' },
    { name: 'Lime', hex: '#00FF00' },
    { name: 'Lawn Green', hex: '#7CFC00' },
    { name: 'Chartreuse', hex: '#7FFF00' },
    { name: 'Yellow Green', hex: '#9ACD32' },

    { name: 'Medium Slate Blue', hex: '#7B68EE' },
    { name: 'Medium Purple', hex: '#9370DB' },
    { name: 'Blue Violet', hex: '#8A2BE2' },
    { name: 'Indigo', hex: '#4B0082' },
    { name: 'Dark Violet', hex: '#9400D3' },
    { name: 'Dark Orchid', hex: '#9932CC' },
    { name: 'Medium Orchid', hex: '#BA55D3' },
    { name: 'Purple', hex: '#A020F0' },
    { name: 'Dark Magenta', hex: '#8B008B' },
    { name: 'Fuchsia/Magenta', hex: '#FF00FF' },
    { name: 'Violet', hex: '#EE82EE' },
    { name: 'Orchid', hex: '#DA70D6' },
    { name: 'Plum', hex: '#DDA0DD' },

    { name: 'Medium Violet Red', hex: '#C71585' },
    { name: 'Deep Pink', hex: '#FF1493' },
    { name: 'Hot Pink', hex: '#FF69B4' },
    { name: 'Pale Violet Red', hex: '#DB7093' },
    { name: 'Light Pink', hex: '#FFB6C1' },
    { name: 'Pink', hex: '#FFC0CB' },

    { name: 'Light Coral', hex: '#F08080' },
    { name: 'Crimson', hex: '#DC143C' },
    { name: 'Maroon', hex: '#800000' },
    { name: 'Dark Red', hex: '#8B0000' },
    { name: 'Fire Brick', hex: '#B22222' },
    { name: 'Brown', hex: '#A52A2A' },
    { name: 'Salmon', hex: '#FA8072' },
    { name: 'Dark Salmon', hex: '#E9967A' },
    { name: 'Light Salmon', hex: '#FFA07A' },
    { name: 'Coral', hex: '#FF7F50' },
    { name: 'Tomato', hex: '#FF6347' },
    { name: 'Red', hex: '#FF0000' },
    { name: 'Orange Red', hex: '#FF4500' },
    { name: 'Dark Orange', hex: '#FF8C00' },
    { name: 'Orange', hex: '#FFA500' },
    { name: 'Gold', hex: '#FFD700' },
    { name: 'Yellow', hex: '#FFFF00' },
    { name: 'Khaki', hex: '#F0E68C' },
];